name: Build and deploy Django app to Azure Web App - hdgroup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations and collectstatic
        run: |
          source venv/bin/activate
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

      - name: Zip app for deployment
        run: |
          zip -r release.zip . -x "venv/*" ".git/*" "*.pyc" "__pycache__/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write         # ✅ Required for OIDC login
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-zip

      - name: List files (debug)
        run: ls -la

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7E7627668B564A70A892A23CC2FC1031 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0E6BD93C2B64417593AC3D6A9DC96044 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_812B65363C70405C845918CFC51AF20A }}

      - name: Deploy app using zip
        run: |
          az webapp deploy \
            --resource-group hd \
            --name hdgroup \
            --src-path release.zip \
            --type zip
